import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Card from '../components/card';
// import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: 'fsq3+j07IcD0ao3ypLtNdI6Qt8O5+oXBYoHOf3dJByPWsD8=',
    },
  };

  const response = await fetch(
    'https://api.foursquare.com/v3/places/search?query=coffee&ll=52.52%2C13.39&limit=6',
    options
  );

  const data = await response.json();
  console.log(data.results);

  return {
    props: { coffeeStores: data.results },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('Banner btn clicked');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Stores / Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero.png' width={700} height={400} />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Tehran stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
